core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('application.router')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += static(
    settings.STATIC_URL, document_root=settings.STATIC_ROOT)

application/models.py
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.contrib.auth.models import AbstractUser, BaseUserManager
from django.db.models import Count

# Create your models here.


class UsuarioManager(BaseUserManager):

    use_in_migrations = True

    def _create_user(self, email, password, **extra_fields):

        if not email:
            raise ValueError("O e-mail é progratório")

        email = self.normalize_email(email)
        user = self.model(email=email, username=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email, password=None, **extra_fields):
        extra_fields.setdefault('is_superuser', False)
        return self._create_user(email, password, **extra_fields)

    def create_superuser(self, email, password=None, **extra_fields):
        extra_fields.setdefault('is_superuser', True)
        extra_fields.setdefault('is_staff', True)

        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser precisa ter is_superuser=True')

        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser precisa ter is_staff=True')

        return self._create_user(email, password, **extra_fields)


class Profissional(AbstractUser):

    nome = models.CharField('Nome', max_length=100, blank=True)
    foto_perfil = models.ImageField(upload_to='perfil/', null=True, blank=True)
    data_nascimento = models.DateField('Data de Nascimento', null=True)
    especialidade = models.CharField('Especialidade', max_length=100)
    celular = models.CharField('Celular', max_length=20)
    pais = models.CharField('Pais', max_length=20)
    estado = models.CharField('Estado', max_length=100)
    cidade = models.CharField('Cidade', max_length=100)
    email = models.EmailField('E-mail', unique=True)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    def __str__(self) -> str:
        return f"{self.nome} - {self.email}"

    objects = UsuarioManager()


class Paciente(models.Model):
    nome = models.CharField(max_length=100)
    foto_perfil = models.ImageField(upload_to='perfil/', null=True, blank=True)
    data_nascimento = models.DateField()
    especialidade = models.CharField(max_length=100)
    data_cadastro = models.DateField(auto_now_add=True)
    profissional = models.ForeignKey(Profissional, on_delete=models.CASCADE)
    diagnostico = models.CharField(max_length=100)

    class Meta:
        verbose_name = 'Paciente'
        verbose_name_plural = 'Pacientes'

    def __str__(self):
        return self.nome


class Programa(models.Model):
    nome = models.CharField(max_length=100)
    profissional = models.ForeignKey(Profissional, on_delete=models.CASCADE)
    numero_sessoes = models.PositiveIntegerField()
    numero_tentativas = models.PositiveIntegerField()

    class Meta:
        verbose_name = 'Programa'
        verbose_name_plural = 'Programas'

    def __str__(self):
        return self.nome


class ProgramaPaciente(models.Model):
    programa = models.ForeignKey(Programa, on_delete=models.CASCADE)  # noqa
    paciente = models.ForeignKey(Paciente, on_delete=models.CASCADE)

    class Meta:
        verbose_name = 'Programa-Paciente'
        verbose_name_plural = 'Programas-Paciente'

    def __str__(self):
        return self.programa.nome


class Sessao(models.Model):
    nome = models.CharField(max_length=100)
    programa = models.ForeignKey(ProgramaPaciente, on_delete=models.CASCADE)

    class Meta:
        verbose_name = 'Sessão'
        verbose_name_plural = 'Sessões'

    def __str__(self):
        return self.nome


class Tentativa(models.Model):
    nome = models.CharField(max_length=100)
    SITUACAO_CHOICES = [
        ('Sim', 'Sim'),
        ('Não', 'Não'),
        ('Suporte', 'Suporte'),
    ]

    sessao = models.ForeignKey(Sessao, on_delete=models.CASCADE, related_name='sessão')  # noqa
    situacao = models.CharField(max_length=20, choices=SITUACAO_CHOICES, null=True, blank=True)  # noqa
    criado = models.DateField('Data de criação', auto_now_add=True)
    modificado = models.DateField('Data de Atualização', auto_now=True)

    class Meta:
        verbose_name = 'Tentativa'
        verbose_name_plural = 'Tentativas'

    def __str__(self):
        return self.nome


@receiver(post_save, sender=ProgramaPaciente)
def criar_sessoes(sender, instance: ProgramaPaciente, created, **kwargs):
    if created:

        numero_sessao = 1
        for _ in range(instance.programa.numero_sessoes):

            sessao = Sessao.objects.create(nome=f"Sessão {numero_sessao}", programa=instance)  # noqa

            numero_tentativa = 1
            for _ in range(instance.programa.numero_tentativas):
                Tentativa.objects.create(nome=f"{numero_tentativa}ª tentativa - Sessão {numero_sessao}", sessao=sessao)  # noqa
                numero_tentativa += 1
            numero_sessao += 1

application/forms/login.py
from django import forms


class LoginForm(forms.Form):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

    email = forms.EmailField(
        required=False,
        widget=forms.TextInput(attrs={
            'placeholder': "email@exemplo.com",
            'class': "bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-blue-600 focus:border-blue-600 block w-full p-2.5",  # noqa
            'autocomplete': "off"
        }))

    password = forms.CharField(
        required=False,
        widget=forms.PasswordInput(attrs={
            'placeholder': "••••••••",
            'class': "bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-blue-600 focus:border-blue-600 block w-full p-2.5",  # noqa
            'autocomplete': "off"
        }))

application/forms/programa_patiente.py
from django import forms
from application.models import ProgramaPaciente


class ProgramaPacienteForm(forms.ModelForm):
    class Meta:
        model = ProgramaPaciente
        fields = ['programa', 'paciente']

application/forms/registro_area_admin.py
from django.contrib.auth.forms import UserCreationForm
from application.models import Profissional

# FORMULÁRIOS PARA A CRIAÇÃO DE USUÁRIO NA ÁREA ADMINISTRATIVA


class CustomProfissionalCreateForm(UserCreationForm):
    fields = ('first_name', 'last_name', 'fone')

    class Meta:
        model = Profissional
        labels = {'username': 'Username/E-mail'}
        fields = ('first_name', 'last_name', 'celular')

    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        user.email = self.cleaned_data["username"]
        if commit:
            user.save()
        return user

application/forms/sessao.py
from django import forms
from application.models import Sessao


class SessaoForm(forms.ModelForm):
    class Meta:
        model = Sessao
        fields = ['nome', 'programa']

application/forms/tentativa.py
from django import forms
from application.models import Tentativa


class TentativaForm(forms.ModelForm):
    class Meta:
        model = Tentativa
        fields = ['sessao', 'situacao']

application/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login, logout
from django.shortcuts import get_object_or_404
from . import forms
from . import models
from django.http import Http404
from datetime import date
from itertools import accumulate

# PÁGINAS EXTERNAS DO APP


# LOGIN
def login_page(request):
    form = forms.LoginForm()

    if request.user.is_authenticated:
        return redirect('application:principal')

    return render(request, 'login.html', {
        'form': form,
        'form_action': 'application:autenticar'
    })


def login_redirect_page(request):

    if not request.POST:
        raise Http404()

    form = forms.LoginForm(request.POST)

    if form.is_valid():
        authenticated_user = authenticate(
            username=form.cleaned_data.get('email', ''),
            password=form.cleaned_data.get('password', ''),
        )

        if authenticated_user is not None:
            login(request, authenticated_user)
            return redirect("application:principal")
        else:
            messages.error(request, 'Credenciais inválidas')
    else:
        messages.error(request, 'Usuário ou senha inválidos')

    return render(request, 'login.html', {'form': form})


# CADASTRO
def signup_page(request):
    register_form_data = request.session.get('register_form_data', None)
    form = forms.RegisterForm(register_form_data)

    return render(request, 'cadastro.html', {'form': form})


def signup_redirect(request):

    if not request.POST:
        raise Http404()

    POST = request.POST
    request.session['register_form_data'] = POST

    form = forms.RegisterForm(POST, request.FILES)

    if form.is_valid():
        form.save()

        messages.success(request, "Usuário cadastrado com sucesso!")
        del (request.session['register_form_data'])
        return redirect("application:index")

    return redirect("application:cadastro")


# PÁGINAS INTERNAS DO APP


# PAGINA INICIAL
@login_required(login_url='application:index')
def main_page(request):

    # Consulta para contar a quantidade de pacientes do usuário
    total_pacientes = models.Paciente.objects.filter(
        profissional=request.user).count()

    # Consulta para contar a quantidade de programas do usuário
    total_programas = models.Programa.objects.filter(
        profissional=request.user).count()

    # Buscas os pacientes do usuário
    pacientes = models.Paciente.objects.filter(
        profissional=request.user
    )

    context = {
        'total_pacientes': total_pacientes,
        'total_programas': total_programas,
        'pacientes': pacientes
    }
    return render(request, 'painel_principal.html', context)


# SAIR
@login_required(login_url='application:index', redirect_field_name='next')
def logout_view(request):
    logout(request)
    return redirect('application:index')


# CADASTRO DE PROGRAMA
@login_required(login_url='application:index')
def add_program_page(request):
    register_form_data = request.session.get('register_form_data', None)
    form = forms.ProgramaForm(register_form_data)
    context = {'form': form}
    return render(request, 'cadastro_programa.html', context)


@login_required(login_url='application:index')
def add_program_redirect(request):

    if not request.POST:
        raise Http404()

    POST = request.POST
    request.session['register_form_data'] = POST

    form = forms.ProgramaForm(POST)

    if form.is_valid():
        form.save()
        messages.success(request, "Programa cadastrado com sucesso!")
        del (request.session['register_form_data'])

    if not form.is_valid():
        for field, errors in form.errors.items():
            for error in errors:
                # Faça algo com cada mensagem de erro
                print(f"Erro no campo {field}: {error}")

    return redirect("application:cadastrar-programa")


# CADASTRO DE PACIENTE
@login_required(login_url='application:index')
def add_paciente_page(request):
    register_form_data = request.session.get('register_form_data', None)

    form = forms.PacienteForm(register_form_data)
    data_atual = date.today().strftime("%d/%m/%Y")
    context = {
        'form': form,
        'data_atual': data_atual
    }
    return render(request, 'cadastro_paciente.html', context)


@login_required(login_url='application:index')
def add_paciente_redirect(request):

    if not request.POST:
        raise Http404()
    POST = request.POST
    request.session['register_form_data'] = POST

    form = forms.PacienteForm(POST, request.FILES)

    if form.is_valid():
        form.save()
        messages.success(request, "Paciente cadastrado com sucesso!")
        del (request.session['register_form_data'])

    if not form.is_valid():
        for field, errors in form.errors.items():
            for error in errors:
                print(f"Erro no campo {field}: {error}")

    return redirect("application:cadastrar-paciente")


# BUSCAr PACIENTE
@login_required(login_url='application:index')
def search_main_page(request):

    if request.method == 'POST':

        paciente_id = int(request.POST.get('paciente'))

        # Verificar se o ID do paciente foi fornecido
        if paciente_id > 0:
            try:
                paciente = models.Paciente.objects.get(id=paciente_id)
                return redirect("application:paciente", paciente=paciente.id)

            except models.Paciente.DoesNotExist:
                return redirect("application:principal")

        else:
            # Caso o ID do paciente não tenha sido fornecido
            mensagem = 'Selecione um paciente.'
            messages.error(request, mensagem)
            return redirect("application:principal")

    return redirect("application:principal")


@login_required(login_url='application:index')
def paciente_page(request, paciente):
    try:
        paciente = models.Paciente.objects.get(
            id=paciente, profissional=request.user.id)
    except models.Paciente.DoesNotExist:
        raise Http404()

    programas = models.Programa.objects.filter(
        profissional=request.user)

    context = {
        'paciente': paciente,
        'programas': programas
    }

    return render(request, 'dados_paciente.html', context)


# EDIÇÃO DE PACIENTE
@login_required(login_url='application:index')
def edit_paciente_page(request, id):

    try:
        paciente = models.Paciente.objects.get(
            id=id, profissional=request.user.id)
    except models.Paciente.DoesNotExist:
        raise Http404()

    register_form_data = request.session.get('register_form_data', None)

    form = forms.PacienteForm(register_form_data, instance=paciente)
    data = str(paciente.data_cadastro)
    data = data.split('-')
    nova_data = data[2] + '/' + data[1] + '/' + data[0]
    context = {
        'form': form,
        'paciente': paciente,
        'data_atual': nova_data
    }

    return render(request, 'editar_paciente.html', context)


@login_required(login_url='application:index')
def edit_paciente_redirect(request, id):

    paciente = get_object_or_404(
        models.Paciente, id=id, profissional=request.user.id)

    POST = request.POST
    request.session['register_form_data'] = POST

    form = forms.PacienteForm(POST, request.FILES, instance=paciente)

    if form.is_valid():
        form.save()

        messages.success(request, "Paciente modificado com sucesso!")
        del (request.session['register_form_data'])

    if not form.is_valid():
        for field, errors in form.errors.items():
            for error in errors:
                print(f"Erro no campo {field}: {error}")

    return redirect('application:editar-paciente', id)


# VINCULAR PACIENTE PROGRAMA
@login_required(login_url='application:index')
def add_programa_paciente(request, id):

    if not request.POST:
        raise Http404()

    paciente_id = int(request.POST.get('paciente'))
    programa_id = int(request.POST.get('programa'))

    if programa_id <= 0:
        messages.error(request, "Selecione um programa.")
        return redirect('application:paciente', paciente_id)

    # verificação adicional
    if int(id) != int(paciente_id):
        return redirect('application:paciente', id)

    paciente = get_object_or_404(
        models.Paciente, id=paciente_id, profissional=request.user.id)

    programa = get_object_or_404(
        models.Programa, id=programa_id, profissional=request.user.id)

    programa_paciente, created = models.ProgramaPaciente.objects.get_or_create(
        programa=programa, paciente=paciente)

    return redirect('application:programa-paciente', paciente.id, programa_paciente.id)  # noqa


# VINCULAR PACIENTE PROGRAMA
@login_required(login_url='application:index')
def programa_paciente(request, id_paciente, id_programa):

    programa_paciente = get_object_or_404(
        models.ProgramaPaciente, id=id_programa, programa__profissional=request.user.id)  # noqa

    sessoes = models.Sessao.objects.filter(programa=programa_paciente)

    if request.method == 'POST':

        sessao_valor = int(request.POST.get('SelectSessao'))

        if sessao_valor <= 0:
            context = {
                'id_paciente': id_paciente,
                'programa_paciente': programa_paciente,
                'sessoes': sessoes
            }
            return render(request, 'programa.html', context)

        busca_sessao = get_object_or_404(models.Sessao, id=sessao_valor)
        tentativas = models.Tentativa.objects.filter(sessao=busca_sessao)

        context = {
            'id_paciente': id_paciente,
            'programa_paciente': programa_paciente,
            'sessoes': sessoes,
            'busca_sessao': busca_sessao,
            'tentativas': tentativas
        }

        return render(request, 'programa.html', context)

    context = {
        'id_paciente': id_paciente,

application/templates/cadastro.html
{% load static %}
<!doctype html>
<html lang="pt-br">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <script src="https://cdn.tailwindcss.com"></script>
  <title>Somare - Cadastro </title>
</head>

<body class="bg-indigo-950" onload="listarSelects()">
  <section class="">
    <div class="flex flex-col items-center mt-5 mb-5 px-6">
      <div class="flex justify-between items-center w-full sm:p-0 sm:max-w-md mb-5">
        <div>
          <a href="{% url 'application:index' %}" class="flex hover:underline text-white cursor-pointer">
            <svg class="inline w-5 h-5 mb-1.5 mr-1" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24"
              stroke-width="1.5" stroke="currentColor">
              <path stroke-linecap="round" stroke-linejoin="round" d="M9 15L3 9m0 0l6-6M3 9h12a6 6 0 010 12h-3" />
            </svg>
            Voltar
          </a>
        </div>
      </div>
      <div class="w-full bg-white rounded-lg shadow sm:max-w-md p-2">
        <div class="p-6 space-y-4">
          <div class="flex justify-center mb-6 text-lg sm:text-2xl font-semibold text-gray-900 ">
            <img class="w-8 h-8 mr-2" src="{% static 'images/antigo.png' %}" alt="logo" />
            Cadastro
          </div>

          <div class="w-full text-center">
            <span class="block mb-2 font-medium">Foto do Perfil</span>
            <img src="{% static 'images/user-icon.png' %}" id="IconFotoPaciente"
              class="bg-gray-200 mx-auto rounded-full w-24 h-24 p-0.5" alt="img_paciente" />
            <span id="FotoPacienteError" class="hidden block mt-1 text-red-500 p-2">Tipo de arquivo não suportado. <br>
              Por favor, selecione um arquivo JPEG, PNG ou JPG.</span>
          </div>

          <form method="POST" action="{% url 'application:redirect' %}" class="space-y-4" enctype="multipart/form-data"
            onsubmit="formatarDados(event)">
            {% csrf_token %}
            <input type="hidden" name="profissional" value="{{ request.user.id }}">
            <div>
              <label for="{{ form.foto_perfil.id_for_label }}"
                class="text-center text-white bg-blue-600 hover:bg-blue-700 block font-medium rounded-lg text-sm px-5 py-3 h-12 cursor-pointer">
                <span>Selecionar Foto</span>
                <!-- input type="file" accept="image/jpeg, image/png, image/jpg" id="FotoPaciente" name="FotoPaciente" oninput="changePhoto()" class="hidden"/-->
                {{ form.foto_perfil }}
              </label>
            </div>
            <div>
              <label for="{{ form.nome.id_for_label }}" class="block mb-2 text-sm font-medium text-gray-900 ">Nome
                Profissional</label>
              <!-- input type="text" id="NomeProfissional" name="NomeProfissional" oninput="formatarNome('NomeProfissional')" class="bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-blue-600 focus:border-blue-600 block w-full p-2.5 " placeholder="Nome" required/ -->
              {{form.nome}}
              <span class="block mb-2 text-sm text-red-900">{{ form.nome.errors }}</span>
            </div>

            <div>
              <label for="{{ form.data_nascimento.id_for_label }}"
                class="block mb-2 text-sm font-medium text-gray-900 ">Data de Nascimento</label>
              <!-- input type="text" placeholder="dd/mm/aaaa" maxlength="11" oninput="formatarData('DataNascimento')" id="DataNascimento" name="DataNascimento" class="bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-blue-600 focus:border-blue-600 block w-full p-2.5 " required/ -->
              {{ form.data_nascimento }}
              <span class="block mb-2 text-sm text-red-900">{{ form.data_nascimento.errors }}</span>
            </div>

            <div>
              <label for="{{ form.especialidade.id_for_label }}"
                class="block mb-2 text-sm font-medium text-gray-900 ">Especialidade</label>
              <!-- select id="SelectEspecialidade" name="SelectEspecialidade" class="bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-blue-600 focus:border-blue-600 block w-full p-2.5">
                  <option>Selecione a Especialidade</option>
                  <option>Psicologia</option>
                </select -->
              {{ form.especialidade }}
              <span class="block mb-2 text-sm text-red-900">{{ form.especialidade.errors }}</span>
            </div>

            <div>
              <label for="{{ form.celular.id_for_label }}"
                class="block mb-2 text-sm font-medium text-gray-900 ">Celular</label>
              <!-- input type="text" id="celular" name="celular" maxlength="15" oninput="formatarNumeroCelular('celular')" class="bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-blue-600 focus:border-blue-600 block w-full p-2.5 " placeholder="(99) 99999-9999" required/-->
              {{ form.celular }}
              <span class="block mb-2 text-sm text-red-900">{{ form.celular.errors }}</span>
            </div>

            <div>
              <label for="{{ form.pais.id_for_label }}"
                class="block mb-2 text-sm font-medium text-gray-900 ">Pais</label>
              <!--select id="SelectPais" name="SelectPais" class="bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-blue-600 focus:border-blue-600 block w-full p-2.5" disabled>
                  <option value="Brasil" selected>Brasil</option>
                </select -->
              {{ form.pais }}
              <span class="block mb-2 text-sm text-red-900">{{ form.pais.errors }}</span>
            </div>

            <div>
              <label for="{{ form.estado.id_for_label }}"
                class="block mb-2 text-sm font-medium text-gray-900 ">Estado</label>
              <div id="SelectEstadoInputDiv">
                <select id="id_estado" oninput="listarCidades()" name="estado"
                  class="bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-blue-600 focus:border-blue-600 block w-full p-2.5 ">
                  <option selected value="null">Selecione o Estado</option>
                </select>
                <!-- {{ form.estado }} -->
                <span class="block mb-2 text-sm text-red-900">{{ form.estado.errors }}</span>
              </div>
            </div>

            <div>
              <label for="{{ form.cidade.id_for_label }}"
                class="block mb-2 text-sm font-medium text-gray-900 ">Cidade</label>
              <div id="SelectCidadeInputDiv">
                <select id="id_cidade" name="cidade"
                  class="bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-blue-600 focus:border-blue-600 block w-full p-2.5 ">
                  <option selected value="null">Selecione a Cidade</option>
                </select>
                <!--{{ form.cidade }}-->
                <span class="block mb-2 text-sm text-red-900">{{ form.cidade.errors }}</span>
              </div>
            </div>

            <div>
              <label for="{{ form.email.id_for_label }}"
                class="block mb-2 text-sm font-medium text-gray-900 ">Email</label>
              <!-- input type="email" id="email" name="email" oninput="validarEmail('email')" class="bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-blue-600 focus:border-blue-600 block w-full p-2.5 " placeholder="email@exemplo.com" required/ -->
              {{ form.email }}
              <span class="block mb-2 text-sm text-red-900">{{ form.email.errors }}</span>
            </div>

            <div>
              <label for="{{ form.password.id_for_label }}"
                class="block mb-2 text-sm font-medium text-gray-900">Senha</label>
              <div class="relative">
                {{ form.password }}
                <!-- input id="Senha" name="Senha" type="password" placeholder="••••••••" class="bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-blue-600 focus:border-blue-600 block w-full p-2.5" required/ -->
                <span id="toggle-senha-icon" name="toggle-senha-icon" class="absolute right-4 bottom-2.5"
                  onclick="visibilidadeSenha('id_password', 'toggle-senha-icon')">
                  <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5"
                    stroke="currentColor" class="w-6 h-6">
                    <path stroke-linecap="round" stroke-linejoin="round"
                      d="M2.036 12.322a1.012 1.012 0 010-.639C3.423 7.51 7.36 4.5 12 4.5c4.638 0 8.573 3.007 9.963 7.178.07.207.07.431 0 .639C20.577 16.49 16.64 19.5 12 19.5c-4.638 0-8.573-3.007-9.963-7.178z" />
                    <path stroke-linecap="round" stroke-linejoin="round" d="M15 12a3 3 0 11-6 0 3 3 0 016 0z" />
                  </svg>
                </span>
              </div>
              <span class="block mb-2 text-sm text-red-900">{{ form.password.errors }}</span>
            </div>

            <div>
              <label for="{{ form.password2.id_for_label }}" class="block mb-2 text-sm font-medium text-gray-900">Senha
                novamente</label>
              <div class="relative">
                {{ form.password2 }}
                <!-- input type="password" id="senhaConfirm" name="senhaConfirm" placeholder="••••••••" class="bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-blue-600 focus:border-blue-600 block w-full p-2.5" required/ -->
                <span id="toggle-senhaConfirm-icon" name="toggle-senhaConfirm-icon" class="absolute right-4 bottom-2.5"
                  onclick="visibilidadeSenha('id_password2', 'toggle-senhaConfirm-icon')">
                  <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5"
                    stroke="currentColor" class="w-6 h-6">
                    <path stroke-linecap="round" stroke-linejoin="round"
                      d="M2.036 12.322a1.012 1.012 0 010-.639C3.423 7.51 7.36 4.5 12 4.5c4.638 0 8.573 3.007 9.963 7.178.07.207.07.431 0 .639C20.577 16.49 16.64 19.5 12 19.5c-4.638 0-8.573-3.007-9.963-7.178z" />
                    <path stroke-linecap="round" stroke-linejoin="round" d="M15 12a3 3 0 11-6 0 3 3 0 016 0z" />
                  </svg>
                </span>
              </div>
              <span class="block mb-2 text-sm text-red-900">{{ form.password2.errors }}</span>
            </div>

            <div class="flex items-start">
              <!--
              <div class="flex items-center h-5">
                <input id="TemosUso" name="TemosUso" aria-describedby="remember" type="checkbox"
                  class="w-4 h-4 border border-gray-300 rounded bg-gray-50" required />
              </div>
              <div class="ml-3 text-sm">
                <label for="TemosUso" class="text-gray-500 ">Você concorda com os <a href="#"
                    class="text-blue-600 hover:underline">Termos de Uso</a>?</label>
              </div>
              -->
            </div>

            <button type="submit"
              class="block w-full text-white bg-blue-600 hover:bg-blue-700 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-3 text-center h-12">
              Cadastrar
            </button>
          </form>

          <p class="text-center text-sm font-medium">Já tem conta?
            <a href="{% url 'application:index' %}"
              class="hover:underline text-blue-600 font-medium inline-flex space-x-1 items-center"><span>Logar </span>
              <span>
                <svg xmlns="http://www.w3.org/2000/svg" class="h-4 w-4" fill="none" viewBox="0 0 24 24"
                  stroke="currentColor" stroke-width="2">
                  <path stroke-linecap="round" stroke-linejoin="round"
                    d="M10 6H6a2 2 0 00-2 2v10a2 2 0 002 2h10a2 2 0 002-2v-4M14 4h6m0 0v6m0-6L10 14" />
                </svg>
              </span>
            </a>
          </p>
        </div>
      </div>
    </div>
  </section>
  <script src="{% static 'js/scripts.js' %}"></script>

</html>